# Generated by Django 3.1 on 2024-04-27 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_auto_20240416_0159'),
        ('category', '0003_auto_20240416_0129'),
    ]

    operations = [
    ]
